name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: 767397899756.dkr.ecr.eu-north-1.amazonaws.com
          ECR_REPOSITORY: shizotrack
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Download ECS task definition
        run: |
          aws ecs describe-task-definition --task-definition shizotrack > ecs_task_definition.json

      - name: Fill in the new image ID in the ECS task definition
        run: |
          sed -i 's|767397899756.dkr.ecr.eu-north-1.amazonaws.com/shizotrack:latest|767397899756.dkr.ecr.eu-north-1.amazonaws.com/shizotrack:latest|g' ecs_task_definition.json

      - name: Register new task definition
        run: |
          aws ecs register-task-definition --cli-input-json file://ecs_task_definition.json

      - name: Deploy to Amazon ECS
        run: |
          aws ecs update-service --cluster shizotrack4 --service shizotrack --force-new-deployment
